packages:
  - "apps/*"
  - "packages/*"

catalog:
  # Aptos ecosystem
  "@aptos-labs/ts-sdk": ^6.0.0
  "@aptos-labs/wallet-standard": ^0.5.2
  "@aptos-labs/gas-station-client": ^2.0.3

  # Build tools
  typescript: ^5.9.3
  tsup: ^8.4.0
  eslint: ^8.57.1
  eslint-config-next: ^14.2.3
  prettier: ^3.6.2

  # Testing
  vitest: ^2.1.8
  happy-dom: ^20.0.2
  "@testing-library/jest-dom": ^6.0.0
  "@testing-library/react": ^15
  "@testing-library/user-event": ^14.0.0

  # Type definitions
  "@types/node": ^22
  "@types/react": ^19
  "@types/react-dom": ^19

  # CSS/styling tools
  autoprefixer: ^10.4.19
  postcss: ^8.4.38
  tailwindcss: ^3.4.1

  # Solana
  "@solana/wallet-adapter-base": ^0.9.23
  "@solana/wallet-standard-wallet-adapter-base": ^1.1.4
  "@solana/web3.js": ^1.95.8

  # Sui
  "@mysten/sui": ^1.24.0
  "@mysten/wallet-standard": ^0.13.29

  # Wormhole
  "@wormhole-foundation/sdk": ^4.7.1
  "@wormhole-foundation/sdk-aptos": ^4.7.1
  "@wormhole-foundation/sdk-solana": ^4.7.1

  # Wallet standard
  "@wallet-standard/app": ^1.1.0

  # Common libraries
  tweetnacl: ^1.0.3
  ethers: ^6.13.5
  eventemitter3: ^4.0.7
  buffer: ^6.0.3
  bs58: ^6.0.0
  antd: ^5.18.3

  # React/Next.js
  next: ^15
  react: ^19
  react-dom: ^19
  next-themes: ^0.4.4
  "@tanstack/react-query": ^5.59.16
  "@telegram-apps/sdk": ^2.0.0

  # Radix UI
  "@radix-ui/react-collapsible": ^1.0.3
  "@radix-ui/react-dialog": ^1.0.5
  "@radix-ui/react-dropdown-menu": ^2.0.6
  "@radix-ui/react-label": ^2.0.2
  "@radix-ui/react-radio-group": ^1.1.3
  "@radix-ui/react-slot": ^1.0.2
  "@radix-ui/react-switch": ^1.0.3
  "@radix-ui/react-toast": ^1.1.5

  # UI utilities
  class-variance-authority: ^0.7.0
  clsx: ^2.1.1
  lucide-react: ^0.474.0
  tailwind-merge: ^2.3.0
  tailwindcss-animate: ^1.0.7
