export const mainnetChains = {
  Ethereum: {
    key: "Ethereum",
    id: 2,
    context: "Ethereum",
    finalityThreshold: 64,
    displayName: "Ethereum",
    explorerUrl: "https://etherscan.io/",
    explorerName: "Etherscan",
    gasToken: "ETH",
    chainId: 1,
    icon: "Ethereum",
    maxBlockSearch: 2000,
    symbol: "ETH",
  },
  Solana: {
    key: "Solana",
    id: 1,
    context: "Solana",
    finalityThreshold: 32,
    displayName: "Solana",
    explorerUrl: "https://explorer.solana.com/",
    explorerName: "Solana Explorer",
    gasToken: "SOL",
    chainId: 0,
    icon: "Solana",
    maxBlockSearch: 2000,
    symbol: "SOL",
  },
};

export const AptosMainnetChain = {
  key: "Aptos",
  id: 22,
  context: "Aptos",
  finalityThreshold: 0,
  displayName: "Aptos",
  explorerUrl: "https://explorer.aptoslabs.com/",
  explorerName: "Aptos Explorer",
  gasToken: "APT",
  chainId: 0,
  icon: "Aptos",
  maxBlockSearch: 0,
  symbol: "APT",
};
