import { Context } from "../types";

import { ChainsConfig } from "../types";

export const testnetChains: ChainsConfig = {
  Sepolia: {
    key: "Sepolia",
    id: 10002,
    context: Context.ETH,
    finalityThreshold: 0,
    displayName: "Sepolia",
    explorerUrl: "https://sepolia.etherscan.io/",
    explorerName: "Etherscan",
    gasToken: "ETHsepolia",
    chainId: 11155111,
    icon: "Ethereum",
    maxBlockSearch: 2000,
    symbol: "ETH",
    defaultRpc: "https://eth-sepolia.public.blastapi.io",
    wrappedGasToken: "0xeef12A83EE5b7161D3873317c8E0E7B76e0B5D9c",
  },
  Solana: {
    key: "Solana",
    id: 1,
    context: Context.SOLANA,
    finalityThreshold: 32,
    displayName: "Solana",
    explorerUrl: "https://explorer.solana.com/",
    explorerName: "Solana Explorer",
    gasToken: "SOL",
    chainId: 0,
    icon: "Solana",
    maxBlockSearch: 2000,
    symbol: "SOL",
    defaultRpc: "https://api.devnet.solana.com",
    wrappedGasToken: "So11111111111111111111111111111111111111112",
  },
  // Sui: {
  //   key: "Sui",
  //   id: 21,
  //   context: Context.SUI,
  //   finalityThreshold: 0,
  //   displayName: "Sui",
  //   explorerUrl: "https://suiscan.xyz/testnet/",
  //   explorerName: "Suiscan",
  //   gasToken: "SUI",
  //   chainId: 0,
  //   icon: "Sui",
  //   maxBlockSearch: 0,
  //   symbol: "SUI",
  //   sdkName: "Sui",
  // },
};

export const AptosTestnetChain = {
  key: "Aptos",
  id: 22,
  context: Context.APTOS,
  finalityThreshold: 0,
  displayName: "Aptos",
  explorerUrl: "https://explorer.aptoslabs.com?network=testnet",
  explorerName: "Aptos Explorer",
  gasToken: "APT",
  chainId: 0,
  icon: "Aptos",
  maxBlockSearch: 0,
  symbol: "APT",
  sdkName: "Aptos",
};
