import { Context, ChainsConfig } from "../types";

export const testnetChains: ChainsConfig = {
  Sepolia: {
    key: "Sepolia",
    context: Context.ETH,
    chainId: 11155111,
    displayName: "Sepolia",
    explorerUrl: "https://sepolia.etherscan.io/",
    explorerName: "Etherscan",
    icon: "Ethereum",
    symbol: "ETH",
    defaultRpc: "https://ethereum-sepolia-rpc.publicnode.com",
  },
  BaseSepolia: {
    key: "BaseSepolia",
    context: Context.ETH,
    chainId: 84532,
    displayName: "Base Sepolia",
    explorerUrl: "https://sepolia.basescan.org",
    explorerName: "Basescan",
    icon: "BaseSepolia",
    symbol: "BASE",
    defaultRpc:
      "https://chain-proxy.wallet.coinbase.com?targetName=base-sepolia",
  },
  ArbitrumSepolia: {
    key: "ArbitrumSepolia",
    context: Context.ETH,
    chainId: 421614,
    displayName: "Arbitrum Sepolia",
    explorerUrl: "https://sepolia.arbiscan.io",
    explorerName: "Etherscan",
    icon: "Arbitrum",
    symbol: "ARB",
    defaultRpc: "https://sepolia-rollup.arbitrum.io/rpc",
  },
  Avalanche: {
    key: "Avalanche",
    context: Context.ETH,
    chainId: 43113,
    displayName: "Avalanche Fuji",
    explorerUrl: "https://testnet.snowtrace.io",
    explorerName: "Avascan",
    icon: "Avalanche",
    symbol: "AVAX",
    defaultRpc: "https://api.avax-test.network/ext/bc/C/rpc",
  },
  PolygonSepolia: {
    key: "PolygonSepolia",
    context: Context.ETH,
    chainId: 80002,
    displayName: "Polygon",
    explorerUrl: "https://amoy.polygonscan.com/",
    explorerName: "PolygonScan",
    icon: "Polygon",
    symbol: "MATIC",
    defaultRpc: "https://rpc-amoy.polygon.technology/",
  },
  Solana: {
    key: "Solana",
    context: Context.SOLANA,
    displayName: "Solana",
    explorerUrl: "https://solscan.io",
    explorerName: "Solscan",
    chainId: 0,
    icon: "Solana",
    symbol: "SOL",
    defaultRpc: "https://api.devnet.solana.com",
  },
  Aptos: {
    key: "Aptos",
    context: Context.APTOS,
    displayName: "Aptos",
    explorerUrl: "https://explorer.aptoslabs.com?network=testnet",
    explorerName: "Aptos Explorer",
    chainId: 0,
    icon: "Aptos",
    symbol: "APT",
    defaultRpc: "https://fullnode.testnet.aptos.dev",
  },
  Sui: {
    key: "Sui",
    context: Context.SUI,
    displayName: "Sui",
    explorerUrl: "https://suiscan.xyz/testnet",
    explorerName: "Suiscan",
    chainId: 0,
    icon: "Sui",
    symbol: "SUI",
    defaultRpc: "https://fullnode.testnet.sui.io:443",
  },
};
