import { Context, ChainsConfig } from "../types";

export const mainnetChains: ChainsConfig = {
  Ethereum: {
    key: "Ethereum",
    context: Context.ETH,
    displayName: "Ethereum",
    explorerUrl: "https://etherscan.io/",
    explorerName: "Etherscan",
    chainId: 1,
    icon: "Ethereum",
    symbol: "ETH",
    defaultRpc: "https://rpc.ankr.com/eth",
  },
  Solana: {
    key: "Solana",
    context: Context.SOLANA,
    displayName: "Solana",
    explorerUrl: "https://solscan.io",
    explorerName: "Solscan",
    chainId: 0,
    icon: "Solana",
    symbol: "SOL",
    defaultRpc: "https://solana-rpc.publicnode.com",
  },
  Aptos: {
    key: "Aptos",
    context: Context.APTOS,
    displayName: "Aptos",
    explorerUrl: "https://explorer.aptoslabs.com/",
    explorerName: "Aptos Explorer",
    chainId: 0,
    icon: "Aptos",
    symbol: "APT",
    defaultRpc: "https://fullnode.mainnet.aptos.dev",
  },
  Avalanche: {
    key: "Avalanche",
    context: Context.ETH,
    chainId: 43114,
    displayName: "Avalanche",
    explorerUrl: "https://snowtrace.io",
    explorerName: "Avascan",
    icon: "Avalanche",
    symbol: "AVAX",
    defaultRpc: "https://avalanche-c-chain-rpc.publicnode.com",
  },
  Base: {
    key: "Base",
    context: Context.ETH,
    chainId: 8453,
    displayName: "Base",
    explorerUrl: "https://basescan.org",
    explorerName: "BaseScan",
    icon: "Base",
    symbol: "BASE",
    defaultRpc: "https://mainnet.base.org",
  },
  Arbitrum: {
    key: "Arbitrum",
    context: Context.ETH,
    chainId: 42161,
    displayName: "Arbitrum",
    explorerUrl: "https://arbiscan.io/",
    explorerName: "Arbitrum Explorer",
    icon: "Arbitrum",
    symbol: "ARB",
    defaultRpc: "https://arb1.arbitrum.io/rpc",
  },
  Polygon: {
    key: "Polygon",
    context: Context.ETH,
    chainId: 137,
    displayName: "Polygon",
    explorerUrl: "https://polygonscan.com/",
    explorerName: "PolygonScan",
    icon: "Polygon",
    symbol: "MATIC",
    defaultRpc: "https://polygon-bor-rpc.publicnode.com",
  },
  Sui: {
    key: "Sui",
    context: Context.SUI,
    displayName: "Sui",
    explorerUrl: "https://suiscan.xyz/",
    explorerName: "Suiscan",
    chainId: 0,
    icon: "Sui",
    symbol: "SUI",
    defaultRpc: "https://fullnode.mainnet.sui.io:443",
  },
};
