
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = (T & DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }>)


export const DisplayValue: typeof import("../components/DisplayValue.vue")['default']
export const LabelValueGrid: typeof import("../components/LabelValueGrid.vue")['default']
export const ThemeToggle: typeof import("../components/ThemeToggle.vue")['default']
export const TransactionHash: typeof import("../components/TransactionHash.vue")['default']
export const MultiAgent: typeof import("../components/TransactonFlows/MultiAgent.vue")['default']
export const SingleSigner: typeof import("../components/TransactonFlows/SingleSigner.vue")['default']
export const Sponsor: typeof import("../components/TransactonFlows/Sponsor.vue")['default']
export const TransactionParameters: typeof import("../components/TransactonFlows/TransactionParameters.vue")['default']
export const WalletConnection: typeof import("../components/WalletConnection/WalletConnection.vue")['default']
export const AptosConnectWalletRow: typeof import("../components/WalletSelector/AptosConnectWalletRow.vue")['default']
export const ConnectWalletDialog: typeof import("../components/WalletSelector/ConnectWalletDialog.vue")['default']
export const WalletRow: typeof import("../components/WalletSelector/WalletRow.vue")['default']
export const WalletSelection: typeof import("../components/WalletSelector/WalletSelection.vue")['default']
export const WalletSelector: typeof import("../components/WalletSelector/WalletSelector.vue")['default']
export const WalletIcon: typeof import("../components/ui/Wallet/WalletIcon.vue")['default']
export const WalletLink: typeof import("../components/ui/Wallet/WalletLink.vue")['default']
export const Alert: typeof import("../components/ui/alert/Alert.vue")['default']
export const AlertDescription: typeof import("../components/ui/alert/AlertDescription.vue")['default']
export const AlertTitle: typeof import("../components/ui/alert/AlertTitle.vue")['default']
export const Button: typeof import("../components/ui/button/Button.vue")['default']
export const Card: typeof import("../components/ui/card/Card.vue")['default']
export const CardContent: typeof import("../components/ui/card/CardContent.vue")['default']
export const CardDescription: typeof import("../components/ui/card/CardDescription.vue")['default']
export const CardFooter: typeof import("../components/ui/card/CardFooter.vue")['default']
export const CardHeader: typeof import("../components/ui/card/CardHeader.vue")['default']
export const CardTitle: typeof import("../components/ui/card/CardTitle.vue")['default']
export const Collapsible: typeof import("../components/ui/collapsible/Collapsible.vue")['default']
export const CollapsibleContent: typeof import("../components/ui/collapsible/CollapsibleContent.vue")['default']
export const CollapsibleTrigger: typeof import("../components/ui/collapsible/CollapsibleTrigger.vue")['default']
export const Dialog: typeof import("../components/ui/dialog/Dialog.vue")['default']
export const DialogClose: typeof import("../components/ui/dialog/DialogClose.vue")['default']
export const DialogContent: typeof import("../components/ui/dialog/DialogContent.vue")['default']
export const DialogDescription: typeof import("../components/ui/dialog/DialogDescription.vue")['default']
export const DialogFooter: typeof import("../components/ui/dialog/DialogFooter.vue")['default']
export const DialogHeader: typeof import("../components/ui/dialog/DialogHeader.vue")['default']
export const DialogOverlay: typeof import("../components/ui/dialog/DialogOverlay.vue")['default']
export const DialogScrollContent: typeof import("../components/ui/dialog/DialogScrollContent.vue")['default']
export const DialogTitle: typeof import("../components/ui/dialog/DialogTitle.vue")['default']
export const DialogTrigger: typeof import("../components/ui/dialog/DialogTrigger.vue")['default']
export const DropdownMenu: typeof import("../components/ui/dropdown-menu/DropdownMenu.vue")['default']
export const DropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue")['default']
export const DropdownMenuContent: typeof import("../components/ui/dropdown-menu/DropdownMenuContent.vue")['default']
export const DropdownMenuGroup: typeof import("../components/ui/dropdown-menu/DropdownMenuGroup.vue")['default']
export const DropdownMenuItem: typeof import("../components/ui/dropdown-menu/DropdownMenuItem.vue")['default']
export const DropdownMenuLabel: typeof import("../components/ui/dropdown-menu/DropdownMenuLabel.vue")['default']
export const DropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/DropdownMenuRadioGroup.vue")['default']
export const DropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/DropdownMenuRadioItem.vue")['default']
export const DropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/DropdownMenuSeparator.vue")['default']
export const DropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/DropdownMenuShortcut.vue")['default']
export const DropdownMenuSub: typeof import("../components/ui/dropdown-menu/DropdownMenuSub.vue")['default']
export const DropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/DropdownMenuSubContent.vue")['default']
export const DropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/DropdownMenuSubTrigger.vue")['default']
export const DropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/DropdownMenuTrigger.vue")['default']
export const Label: typeof import("../components/ui/label/Label.vue")['default']
export const RadioGroup: typeof import("../components/ui/radio-group/RadioGroup.vue")['default']
export const RadioGroupItem: typeof import("../components/ui/radio-group/RadioGroupItem.vue")['default']
export const Switch: typeof import("../components/ui/switch/Switch.vue")['default']
export const Toast: typeof import("../components/ui/toast/Toast.vue")['default']
export const ToastAction: typeof import("../components/ui/toast/ToastAction.vue")['default']
export const ToastClose: typeof import("../components/ui/toast/ToastClose.vue")['default']
export const ToastDescription: typeof import("../components/ui/toast/ToastDescription.vue")['default']
export const ToastProvider: typeof import("../components/ui/toast/ToastProvider.vue")['default']
export const ToastTitle: typeof import("../components/ui/toast/ToastTitle.vue")['default']
export const ToastViewport: typeof import("../components/ui/toast/ToastViewport.vue")['default']
export const Toaster: typeof import("../components/ui/toast/Toaster.vue")['default']
export const NuxtWelcome: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ColorScheme: typeof import("../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const NuxtPage: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyDisplayValue: LazyComponent<typeof import("../components/DisplayValue.vue")['default']>
export const LazyLabelValueGrid: LazyComponent<typeof import("../components/LabelValueGrid.vue")['default']>
export const LazyThemeToggle: LazyComponent<typeof import("../components/ThemeToggle.vue")['default']>
export const LazyTransactionHash: LazyComponent<typeof import("../components/TransactionHash.vue")['default']>
export const LazyMultiAgent: LazyComponent<typeof import("../components/TransactonFlows/MultiAgent.vue")['default']>
export const LazySingleSigner: LazyComponent<typeof import("../components/TransactonFlows/SingleSigner.vue")['default']>
export const LazySponsor: LazyComponent<typeof import("../components/TransactonFlows/Sponsor.vue")['default']>
export const LazyTransactionParameters: LazyComponent<typeof import("../components/TransactonFlows/TransactionParameters.vue")['default']>
export const LazyWalletConnection: LazyComponent<typeof import("../components/WalletConnection/WalletConnection.vue")['default']>
export const LazyAptosConnectWalletRow: LazyComponent<typeof import("../components/WalletSelector/AptosConnectWalletRow.vue")['default']>
export const LazyConnectWalletDialog: LazyComponent<typeof import("../components/WalletSelector/ConnectWalletDialog.vue")['default']>
export const LazyWalletRow: LazyComponent<typeof import("../components/WalletSelector/WalletRow.vue")['default']>
export const LazyWalletSelection: LazyComponent<typeof import("../components/WalletSelector/WalletSelection.vue")['default']>
export const LazyWalletSelector: LazyComponent<typeof import("../components/WalletSelector/WalletSelector.vue")['default']>
export const LazyWalletIcon: LazyComponent<typeof import("../components/ui/Wallet/WalletIcon.vue")['default']>
export const LazyWalletLink: LazyComponent<typeof import("../components/ui/Wallet/WalletLink.vue")['default']>
export const LazyAlert: LazyComponent<typeof import("../components/ui/alert/Alert.vue")['default']>
export const LazyAlertDescription: LazyComponent<typeof import("../components/ui/alert/AlertDescription.vue")['default']>
export const LazyAlertTitle: LazyComponent<typeof import("../components/ui/alert/AlertTitle.vue")['default']>
export const LazyButton: LazyComponent<typeof import("../components/ui/button/Button.vue")['default']>
export const LazyCard: LazyComponent<typeof import("../components/ui/card/Card.vue")['default']>
export const LazyCardContent: LazyComponent<typeof import("../components/ui/card/CardContent.vue")['default']>
export const LazyCardDescription: LazyComponent<typeof import("../components/ui/card/CardDescription.vue")['default']>
export const LazyCardFooter: LazyComponent<typeof import("../components/ui/card/CardFooter.vue")['default']>
export const LazyCardHeader: LazyComponent<typeof import("../components/ui/card/CardHeader.vue")['default']>
export const LazyCardTitle: LazyComponent<typeof import("../components/ui/card/CardTitle.vue")['default']>
export const LazyCollapsible: LazyComponent<typeof import("../components/ui/collapsible/Collapsible.vue")['default']>
export const LazyCollapsibleContent: LazyComponent<typeof import("../components/ui/collapsible/CollapsibleContent.vue")['default']>
export const LazyCollapsibleTrigger: LazyComponent<typeof import("../components/ui/collapsible/CollapsibleTrigger.vue")['default']>
export const LazyDialog: LazyComponent<typeof import("../components/ui/dialog/Dialog.vue")['default']>
export const LazyDialogClose: LazyComponent<typeof import("../components/ui/dialog/DialogClose.vue")['default']>
export const LazyDialogContent: LazyComponent<typeof import("../components/ui/dialog/DialogContent.vue")['default']>
export const LazyDialogDescription: LazyComponent<typeof import("../components/ui/dialog/DialogDescription.vue")['default']>
export const LazyDialogFooter: LazyComponent<typeof import("../components/ui/dialog/DialogFooter.vue")['default']>
export const LazyDialogHeader: LazyComponent<typeof import("../components/ui/dialog/DialogHeader.vue")['default']>
export const LazyDialogOverlay: LazyComponent<typeof import("../components/ui/dialog/DialogOverlay.vue")['default']>
export const LazyDialogScrollContent: LazyComponent<typeof import("../components/ui/dialog/DialogScrollContent.vue")['default']>
export const LazyDialogTitle: LazyComponent<typeof import("../components/ui/dialog/DialogTitle.vue")['default']>
export const LazyDialogTrigger: LazyComponent<typeof import("../components/ui/dialog/DialogTrigger.vue")['default']>
export const LazyDropdownMenu: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenu.vue")['default']>
export const LazyDropdownMenuCheckboxItem: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue")['default']>
export const LazyDropdownMenuContent: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuContent.vue")['default']>
export const LazyDropdownMenuGroup: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuGroup.vue")['default']>
export const LazyDropdownMenuItem: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuItem.vue")['default']>
export const LazyDropdownMenuLabel: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuLabel.vue")['default']>
export const LazyDropdownMenuRadioGroup: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuRadioGroup.vue")['default']>
export const LazyDropdownMenuRadioItem: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuRadioItem.vue")['default']>
export const LazyDropdownMenuSeparator: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuSeparator.vue")['default']>
export const LazyDropdownMenuShortcut: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuShortcut.vue")['default']>
export const LazyDropdownMenuSub: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuSub.vue")['default']>
export const LazyDropdownMenuSubContent: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuSubContent.vue")['default']>
export const LazyDropdownMenuSubTrigger: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuSubTrigger.vue")['default']>
export const LazyDropdownMenuTrigger: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuTrigger.vue")['default']>
export const LazyLabel: LazyComponent<typeof import("../components/ui/label/Label.vue")['default']>
export const LazyRadioGroup: LazyComponent<typeof import("../components/ui/radio-group/RadioGroup.vue")['default']>
export const LazyRadioGroupItem: LazyComponent<typeof import("../components/ui/radio-group/RadioGroupItem.vue")['default']>
export const LazySwitch: LazyComponent<typeof import("../components/ui/switch/Switch.vue")['default']>
export const LazyToast: LazyComponent<typeof import("../components/ui/toast/Toast.vue")['default']>
export const LazyToastAction: LazyComponent<typeof import("../components/ui/toast/ToastAction.vue")['default']>
export const LazyToastClose: LazyComponent<typeof import("../components/ui/toast/ToastClose.vue")['default']>
export const LazyToastDescription: LazyComponent<typeof import("../components/ui/toast/ToastDescription.vue")['default']>
export const LazyToastProvider: LazyComponent<typeof import("../components/ui/toast/ToastProvider.vue")['default']>
export const LazyToastTitle: LazyComponent<typeof import("../components/ui/toast/ToastTitle.vue")['default']>
export const LazyToastViewport: LazyComponent<typeof import("../components/ui/toast/ToastViewport.vue")['default']>
export const LazyToaster: LazyComponent<typeof import("../components/ui/toast/Toaster.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyColorScheme: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/nuxt-island")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.19.0_@parcel+watcher@2.5.1_@types+node@24.5.2_@vue+compiler-sfc@3.5.21_bufferutil@4.0._x5kyn53r34aerms3vpv2ttbspm/node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
